const title = {
    safetyplans: "My SP App Safety Plans",
    firstaid: "General\nInfo",
    maps: "Maps",
    myroster: "My Roster",
    phonetree: "MySP\nSafety\nChat",
    intruderlockdown: "Intruder Lockdown",
    // accidentinjuryillness: "require("../images/accidentinjuryillness.png")",
    afterhoursbuildingemergency: "After Hours Building Emergency",
    bomb: "Bomb",
    deathsuicide: "Death Suicide",
    emergencycutoffs: "Emergency Cutoffs",
    evacuation: "Evacuation",
    fire: "Fire",
    fullsafetyplan: "Full Safety Plan",
    hazardousmaterial: "Hazardous Material",
    homeroom: "Homeroom",
    hostageterrorist: "Hostage Terrorist",
    injuryaccident: "Injury Accident",
    overnighthousing: "Overnight Housing",
    runawayabduction: "Runaway Abduction",
    snow: "Snow",
    studentdisruption: "Student Disruption",
    tornado: "Tornado",
    utilityemergency: "Utility Emergency",
    weapononcampus: "Weapon on Campus",
    admin: "Admin\nPanel",
    group: "My\nGroup",
};

export default title;